-- V10__add_fields_to_productmaster.sql
-- This migration has been merged into V1__baseline_mysql8_inventory_manufacturing.sql
-- Keeping this file empty to avoid Flyway errors if it expects the file to exist.
